documentação numpy: https://numpy.org/devdocs/user/quickstart.html

In [1]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3, 5, 7, 9])

print(a)
print(type(a))

[0 1 2 3 5 7 9]
<class 'numpy.ndarray'>


In [8]:
zero_array = np.zeros(shape = (2,6,6))

print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [9]:
um_array = np.ones((2,3))

print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
vazio = np.empty((3,4))
print(vazio)

[[9.37149010e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.18831764e-312 1.72403890e-047 7.79494629e-071 5.54937499e+170]
 [2.16613014e+184 3.79992242e+175 4.27480978e-033 3.92799191e-033]]


In [16]:
arr = np.arange(start= 10 , step= 2, stop=50)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [20]:
array_linear = np.linspace(0, 100, num=40, retstep=True)

print(array_linear)

(array([  0.        ,   2.56410256,   5.12820513,   7.69230769,
        10.25641026,  12.82051282,  15.38461538,  17.94871795,
        20.51282051,  23.07692308,  25.64102564,  28.20512821,
        30.76923077,  33.33333333,  35.8974359 ,  38.46153846,
        41.02564103,  43.58974359,  46.15384615,  48.71794872,
        51.28205128,  53.84615385,  56.41025641,  58.97435897,
        61.53846154,  64.1025641 ,  66.66666667,  69.23076923,
        71.79487179,  74.35897436,  76.92307692,  79.48717949,
        82.05128205,  84.61538462,  87.17948718,  89.74358974,
        92.30769231,  94.87179487,  97.43589744, 100.        ]), 2.5641025641025643)


In [23]:
a = np.array([1, 2, 3])
print(a)
a2 = a[np.newaxis,:]
print(a2)

[1 2 3]
[[1 2 3]]


In [24]:
a = np.array([1, 2,3])
b = np.array([4, 5, 6])

c = np.concatenate((a,b))
d = np.concatenate((b,a))

print(c)
print(d)


[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [27]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

maior_8 = a[a>8]

print(maior_8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]


In [28]:
a = np.array([1,2,3])

print(a.sum())
print(a.max())
print(a.min())
print(a.mean())

6
3
1
2.0


In [29]:
from numpy.random import default_rng

In [59]:
rng=default_rng()
aleatorio = rng.integers(100, size= (2,4))

print(aleatorio)

[[64 89 51 28]
 [97 82 19 52]]
